### PR TITLE
fix cmake build and simplify return types

### PR DESCRIPTION
**Pull request by Trass3r**

### CODE REVIEW

**Comment by zneak** [comment]
I'm cool with commits 115a34e and 0912bdd but I don't know if I prefer to have the primitive return type at the AST level or the LLVM IR level. IIRC, I changed it to "always structs" because it was simpler with how the old AST code worked, but the new one is much much better at these things, so the ArgumentRecovery pass might be the better place to do that.

**Comment by Trass3r** [comment]
Yeah at least it simplifies the llvm IR and subsequent analysis.
I also played around with the next level of having ptrs in addition to integers. Given that pointers will become opaque this would cover most cases, also this pointers.

**Comment by zneak** [comment]
I dug it up and I first implemented single return values (functions could be `void` or some int type), then when multiple return values hit I switched over to struct or void, then I switched to struct only and that was indeed to make it simpler on the AST side (which is no longer a concern). So yeah, I'd rather have it at the IR level.

I think that it'll be a while before we get the universal pointer type. I'm toying around with type inference but before things get really serious I'm going to implement some long-overdue support for bugpoint.

**Comment by Trass3r** [comment]
Yeah looks like they are currently sorting out byval regarding the new pointer types.

**Comment by zneak** [comment]
I modified the argument recovery pass to make functions return either `void`, a single type, or a struct type.

**Comment by Trass3r** [comment]
ok removed that commit

**Pull request merged**
